services:

  ideal:
    image: ideal:latest
    hostname: ideal
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    env_file:
      - dev.env
    profiles:
      - dev

  postgres:
    image: postgres:16
    hostname: postgres
    ports:
      - "15432:5432"
    env_file:
      - dev.env
    profiles:
      - dep